services:
    app:
        build:
            context: .
            dockerfile: docker/Dockerfile
        container_name: app-url-shortener
        volumes:
            - .:/var/www
        depends_on:
            - db
            - redis

    nginx:
        image: nginx:alpine
        container_name: nginx-url-shortener
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    db:
        image: postgres:latest
        container_name: db-url-shortener
        restart: on-failure
        ports:
            - "5432:5432"
        volumes:
            - db_data:/var/lib/postgresql
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: "0000"
            POSTGRES_DB: url_shortener
    redis:
        image: redis:latest
        container_name: redis-for-url-shortener
        restart: on-failure
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
volumes:
    db_data:
    redis_data:
